### ISSUE TITLE
Google Pay OR Apple Pay button is not showing.

### ISSUE THREAD

**Issue by workatfolium** [stripe-samples/accept-a-payment#1045]
I have successfully created checkout form in php. it 's not showing google pay or apple pay buttons on my checkout form. they both have been by default ON in my dashboard. so what could be the problem.

What i need :
<a href="https://i.imgur.com/a06wtgH.png?1" target="_blank">https://i.imgur.com/a06wtgH.png?1</a>

What i have :
<a href="https://i.imgur.com/FnXl4KA.png?1" target="_blank">https://i.imgur.com/FnXl4KA.png?1</a>

Any Reply Would be Greatly Appreciated.

Thanks.

**Comment by cjavilla-stripe** [comment]
Hey @workatfolium sorry for the delay. Please reach out for support on discord.gg/stripe in the #dev-help channel so we can chat live.
