### ISSUE TITLE
The Swift UI custom payment flow sample does not run in Xcode 14

### ISSUE THREAD

**Issue by justinmichael-stripe** [stripe-samples/accept-a-payment#1295]
Attempting to run the `custom-payment-flow/client/ios-swiftui` sample in Xcode 14 throws two instances of the following error:

```
Stored properties cannot be marked potentially unavailable with '@available'
```

There's also the following warning:

```
'IndexDistance' is deprecated: All index distances are now of type Int
```

![Captured on 2022-10-14 at 10 58 42@2x](https://user-images.githubusercontent.com/49619579/195911865-e4c6d1d7-d6bc-4727-8320-f187ed6b9323.png)

**Comment by cjavilla-stripe** [comment]
This should be fixed now, @justinmichael-stripe. Let us know if there's any other hang ups.
