### ISSUE TITLE
DÖKÜMAN 1

### ISSUE THREAD

**Issue by akasyagroup** [stripe-samples/accept-a-payment#1316]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
not enough information in this issue.
