### ISSUE TITLE
Yemen 

### ISSUE THREAD

**Issue by ww7772** [stripe-samples/accept-a-payment#1359]
# Bug reportY

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
Not enough info.
