### ISSUE TITLE
React native app - lateinit property stripe has not been initialized while getting payment response

### ISSUE THREAD

**Issue by SupriyaKamat** [stripe-samples/accept-a-payment#1406]
![Screenshot_20221202-110035_Wellzio](https://user-images.githubusercontent.com/100405267/205224142-19ce9ec8-002c-4e92-bffb-6a7d0a1e2ee8.jpg)
Getting above issue in android app on clicking payment button

**Comment by paulasjes-stripe** [comment]
If you're still seeing this problem, would you mind opening up an issue over on the [Stripe React Native repo](https://github.com/stripe/stripe-react-native) instead?
