### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by SAGIM37** [stripe-samples/accept-a-payment#1433]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by SAGIM37** [comment]
Good

**Comment by charliegerard-stripe** [comment]
I'm going to close this issue for now as it does not report a real bug. If you need help with anything, please reopen and fill the bug report template.

**Comment by Cjennings83** [comment]
I need help
