### ISSUE TITLE
?????

### ISSUE THREAD

**Issue by vargaslinda** [stripe-samples/accept-a-payment#1447]
[stripe-sample-code (9).zip](https://github.com/stripe-samples/accept-a-payment/files/10253738/stripe-sample-code.9.zip)
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
Not enough context for us to action. Closing.
