### ISSUE TITLE
Bug： Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'arb_id')

### ISSUE THREAD

**Issue by LeeCareFree** [stripe-samples/accept-a-payment#1564]
controller-a03b04ebe66d2345eb5c2670f9f98387.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'arb_id')
    at ws (controller-a03b04ebe66d2345eb5c2670f9f98387.js:1:239287)
    at controller-a03b04ebe66d2345eb5c2670f9f98387.js:1:240705

**Comment by LeeCareFree** [comment]
When I open the proxy, I will report the error！！！

**Comment by cjavilla-stripe** [comment]
Which server and client are you using? Which proxy are you referring to?

**Comment by LeeCareFree** [comment]
> 您使用的是哪个服务器和客户端？你指的是哪个代理？

**Comment by LeeCareFree** [comment]
> Which server and client are you using? Which proxy are you referring to?

hello , I use the "payment-element".  Use the computer's proxy tool to proxy a test domain name.

**Comment by LeeCareFree** [comment]
> Which server and client are you using? Which proxy are you referring to?

You can set up your own proxy to try！

**Comment by LeeCareFree** [comment]
> Which server and client are you using? Which proxy are you referring to?

No problem, I found it was because I blocked a link！Thanks
