### ISSUE TITLE
The python example video isn't available, you can change the docs or upload the video

### ISSUE THREAD

**Issue by obsd** [stripe-samples/accept-a-payment#1945]
# Bug report

## Describe the bug
The Python example video isn't available, you can change the docs or upload the video

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [the python server read me](https://github.com/stripe-samples/accept-a-payment/tree/main/custom-payment-flow/server/python)
2. Click on the youtube video link: https://www.youtube.com/watch?v=Tgjwx-38Dic
3. See error

## Screenshots

![image](https://github.com/stripe-samples/accept-a-payment/assets/1475778/85a4f24d-25d9-4b3e-8ec5-cb88b387544e)

**Comment by paulasjes-stripe** [comment]
Thanks for the report! Fixed in https://github.com/stripe-samples/accept-a-payment/pull/1946
