### ISSUE TITLE
Add disclaimers and restrictions to index and detail views

### ISSUE THREAD

**Issue by cjavilla-stripe** [stripe-samples/accept-a-payment#2]
We need to communicate restrictions like (don't really need to cover all, but most would be good): 

- only works for Stripe accounts in MY 
- only works with X and Y currencies
- only works for X currencies on Stripe accounts in X countries
- only works with https
- only works with specific MCC

**Comment by Cordelro86** [comment]
X

**Comment by Cordelro86** [comment]
X

**Comment by Cordelro86** [comment]
X

**Comment by Cordelro86** [comment]
X

**Comment by Cordelro86** [comment]
Payment

**Comment by Cordelro** [comment]
#323

**Comment by wendylove14700** [comment]
> #323 

ch_3KtgKtFc7yM6jura1Kl3oAhG

**Comment by Abrdjalw** [comment]
https://github.com/stripe-samples/accept-a-payment/issues/2#issuecomment-903539623

**Comment by Abrdjalw** [comment]
#1042

**Comment by Abrdjalw** [comment]
Duplicate of #
