### ISSUE TITLE
Investigating failing CI runs

### ISSUE THREAD

**Issue by hibariya** [stripe-samples/accept-a-payment#377]
According to the outputs of the webservers, the CI does not get the right secret API key these days. I guess the Stripe CLI process is failing due to the same reason. Could you check if the secrets below are set?

* `TEST_STRIPE_PUBLISHABLE_KEY`
* `TEST_STRIPE_SECRET_KEY`

The output of the webserver (Ruby): https://github.com/stripe-samples/accept-a-payment/runs/4062828436#step:6:118
```
web_1       | Your secret API key (STRIPE_SECRET_KEY) is configured incorrectly or
web_1       | doesn't match the expected format.  You can find your API keys in the Stripe
web_1       | dashboard here: https://dashboard.stripe.com/test/apikeys. Then update
web_1       | the .env file.
```

`stripe` process seems exited abnormally: https://github.com/stripe-samples/accept-a-payment/runs/4062828436#step:6:84
```
                  Name                                Command               State    Ports
------------------------------------------------------------------------------------------
accept-a-payment_runner_1                  /work/sample-ci/docker/run ...   Up            
accept-a-payment_runner_run_f839113385d7   /bin/sh -c true                  Exit 0        
accept-a-payment_stripe_1                  /bin/ash -c /bin/stripe -- ...   Exit 1        
accept-a-payment_web_1                     /work/sample-ci/docker/rub ...   Exit 0  
```

**Comment by cjavilla-stripe** [comment]
I think it was related to not having the right priv. I just ran again manually and it looks like it passed many more.

**Comment by hibariya** [comment]
Thanks! That's right. I also missed a couple of other causes of failing CI runs. If my understanding is correct, there are 3 problems:

1. Dependabot PRs cannot retrieve secrets.
2. Some of the e2e tests are failing [like this](https://github.com/stripe-samples/accept-a-payment/runs/4231616611?check_suite_focus=true#step:6:183).
3. Dependabot PRs cancel previous runs on the main branch and [the messages in the Annotations section](https://github.com/stripe-samples/accept-a-payment/actions/runs/1463470602) suggests it's because the concurrency group name is the same between two branches).

**Comment by cjavilla-stripe** [comment]
Hmm. you're right. It looks like the button text may have changed to just `Pay`:


![screenshot_2021-11-16-23-08-57 465](https://user-images.githubusercontent.com/51129155/142294372-ee1d9c20-c6ab-4c66-80fe-ecac43b663e7.png)
