### ISSUE TITLE
OXXO voucher email

### ISSUE THREAD

**Issue by Hans-101** [stripe-samples/accept-a-payment#459]
Hello, 

This is not a bug report, it's a feature request, as per WC customer support:

Currently, the OXXO voucher barcode and ref. number are not included in the order confirmation email (to customer). The voucher only appears as a (Stripe hosted) pop-up after order completion, and there’s no more reference to it, or way to retrieve it.

A logic step would be: as the customer has to go physically to a store, scan the voucher (or provide ref. number), the voucher should be made easily available to the user (i.e. to send it together with the order confirmation email); or at least the unique URL to the hosted Stripe voucher page. Currently, the only option is to print the voucher (not sure who actually prints these days, specially mobile-first users).

We've been in contact with Stripe developers, and it's already baked in their solution, it just needs to be integrated into the plugin. Here are the guidelines and references to make it easier for you:

_I totally understand the need of making the payment process more efficient and practical. There is indeed an option to email the voucher link to your customers, but you may need to have access to edit the integration made by your platform WooCommerce. 

Stripe sends a [payment_intent.requires_action](https://stripe.com/docs/api/events/types#event_types-payment_intent.requires_action) event when an OXXO voucher is created successfully. If you need to email your customers the voucher link, you can [retrieve the PaymentIntent](https://stripe.com/docs/api/payment_intents/retrieve) to get the link upon receiving the event. The `hosted_voucher_url` field in [payment_intent.next_action.oxxo_display_details](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-next_action-oxxo_display_details-hosted_voucher_url) contains the link to the voucher. 

You can see this information in our Docs here:
https://stripe.com/docs/payments/oxxo/accept-a-payment?platform=web#optional:-email-voucher-link-to-your-customer 

Setting up OXXO payment instructions in Spanish by passing the instructions parameter:
https://stripe.com/docs/payments/oxxo/accept-a-payment?platform=web#oxxo-payment-instructions_ 

Hopefully, you can make this happen in near future, as it's only logical for a smooth and practical process.
Thanks

**Comment by Hans-101** [comment]
Shoot, I posted this in the wrong place, please dismiss :)

**Comment by cjavilla-stripe** [comment]
Hey @Hans-101,

Your best bet is actually to write into support: support.stripe.com/contact.

Thanks.
