### ISSUE TITLE
Brooklyn

### ISSUE THREAD

**Issue by liny13415** [stripe-samples/accept-a-payment#555]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by liny13415** [comment]
🙈

**Comment by liny13415** [comment]
_, err := // Go library call

if err != nil {
  // Try to safely cast a generic error to a stripe.Error so that we can get at
  // some additional Stripe-specific information about what went wrong.
  if stripeErr, ok := err.(*stripe.Error); ok {
    // The Code field will contain a basic identifier for the failure.
    switch stripeErr.Code {
      case stripe.ErrorCodeCardDeclined:
      case stripe.ErrorCodeExpiredCard:
      case stripe.ErrorCodeIncorrectCVC:
      case stripe.ErrorCodeIncorrectZip:
      // etc.
    }

    // The Err field can be coerced to a more specific error type with a type
    // assertion. This technique can be used to get more specialized
    // information for certain errors.
    if cardErr, ok := stripeErr.Err.(*stripe.CardError); ok {
      fmt.Printf("Card was declined with code: %v\n", cardErr.DeclineCode)
    } else {
      fmt.Printf("Other Stripe error occurred: %v\n", stripeErr.Error())
    }
  } else {
    fmt.Printf("Other error occurred: %v\n", err.Error())
  }
}

**Comment by cjavilla-stripe** [comment]
Can you add some more context? Not sure what the issue is here.
