### ISSUE TITLE
Docs: How to run the E2E test in the local env.

### ISSUE THREAD

**Issue by hideokamoto-stripe** [stripe-samples/accept-a-payment#583]
This comment is really helpful for us to reproduce the CI error in our local.
https://github.com/stripe-samples/accept-a-payment/pull/15#issuecomment-1025084485

So I'd like to create a Wiki or docs to summarize this instruction.

**Comment by hideokamoto-stripe** [comment]
@hibariya 
I'd like to confirm the testing flow.
Is the following step is correct?

## 1: Configure the env information
Update/create the `.env` file in the project root and set these variables:

```
STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY
STRIPE_SECRET_KEY
DOMAIN=http://web:4242
SERVER_URL=http://web:4242
PRICE=price_xxxx # the price ID you have
```

## 2: Clone the CI project in the repo

```
% git clone ssh://git@github.com/stripe-samples/sample-ci
```

## 3: Build the image that you want to test

```
# custom-payment-flow/server/node & custom-payment-flow/client/html
% ./sample-ci/setup_development_environment custom-payment-flow node ../../client/html

# custom-payment-flow/server/php & custom-payment-flow/client/react
% ./sample-ci/setup_development_environment custom-payment-flow node ../../client/react-cra 
```

## 4: start the testing target application

```
% docker-compose up
```

## 5: Execute the test

```
% docker-compose exec runner bundle exec rspec spec/custom_payment_flow_server_spec.rb
```

## 6-a: change the project

```
% docker-compose down

# Choose the different project dir
% ./sample-ci/setup_development_environment custom-payment-flow node ../../client/react-cra 

% docker-compose up
% docker-compose exec runner bundle exec rspec spec/custom_payment_flow_server_spec.rb
```

## 6-b: Update the env file
```
% docker-compose down
# Choose the same project dir
% ./sample-ci/setup_development_environment custom-payment-flow node ../../client/react-cra 
% docker-compose up
% docker-compose exec runner bundle exec rspec spec/custom_payment_flow_server_spec.rb
```

**Comment by hibariya** [comment]
Thanks for documenting and organizing information!! Let me share a couple of things.

To stop containers for a project/repository, I think `docker-compose stop` would be enough as I commented [here](https://github.com/stripe-samples/accept-a-payment/pull/15#issuecomment-1040818618).

For changing the project, maybe we can suggest the usage by additional examples like these:

```
# repo: subscription-use-cases
./sample-ci/setup_development_environment subscription-use-cases node ../../client/vanillajs # server: node, client: vanillajs

# repo: checkout-one-time-payments
./sample-ci/setup_development_environment . ruby ../../client/html # server: ruby, client: html
```

Let me explain a little more details :memo:  `./sample-ci/setup_development_environment` takes the following 3 arguments:
1. sample: the subdirectory name of the sample on the repo, or `.` if there's only one sample and no subdirectories [like this](https://github.com/stripe-samples/checkout-one-time-payments/blob/745aaa5ed6befc937325675442b8713dcfef1592/.github/workflows/ci.yml#L54).
2. server lang: the directory name of the server-side implementation to use like `ruby`. Currently, sample-ci supports [these ones](https://github.com/stripe-samples/sample-ci/tree/40d79afccf73cb10fee44e7adf138ecd23c71c67/docker).
3. static dir: the relative path from the server-side dir to client dir like `../../client/html` or `../../client/react-cra`.

**Comment by hideokamoto-stripe** [comment]
@hibariya 
I've added a new README.md file to describe the E2E testing steps.
https://github.com/stripe-samples/accept-a-payment/pull/665/files

Could you review the docs?
Thanks!

**Comment by hibariya** [comment]
Thank you! Looks great :+1:
