### ISSUE TITLE
README Documentation Update Required

### ISSUE THREAD

**Issue by comanche** [stripe-samples/accept-a-payment#642]
# Bug report

Documentation update:

`config.ini` should be updated to `.env` in `accept-a-payment/prebuilt-checkout-page/server/php/README.md`

## Describe the bug

The `accept-a-payment/prebuilt-checkout-page/server/php/README.md` references `config.ini` instead of `.env`.

Also make a note that `.env.example` is above the `server` folder and the copied `.env` should be in the `server` folder.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Navigate to https://github.com/stripe-samples/accept-a-payment/tree/main/prebuilt-checkout-page/server/php to see the README.md.

## Expected behavior

`config.ini` should be changed to `.env` and `config.ini.sample` to `.env.example`.

**Comment by cjavdev** [comment]
Thank you!
