### ISSUE TITLE
accept_payment

### ISSUE THREAD

**Issue by vecsdom** [stripe-samples/accept-a-payment#868]
{
  "name": "accept-a-payment",
  "configureDotEnv": true,
  "integrations": [
    {
      "name": "payment-element",
      "clients": ["html", "react-cra"],
      "servers": [
        "ruby",
        "node",
        "python",
        "php",
        "java",
        "go",
        "dotnet",
        "node-typescript"
      ]
    },
    {
      "name": "prebuilt-checkout-page",
      "clients": ["html", "react-cra", "vue-cva"],
      "servers": [
        "ruby",
        "node",
        "python",
        "php",
        "java",
        "go",
        "dotnet"
      ]
    },
    {
      "name": "custom-payment-flow",
      "clients": ["html", "react-cra", "ios", "android-kotlin", "ios-swiftui"],
      "servers": [
        "ruby",
        "node",
        "python",
        "php",
        "java",
        "go",
        "dotnet",
        "node-typescript"
      ]
    }
  ]
}
[stripe-cli-1.8.11.zip](https://github.com/stripe-samples/accept-a-payment/files/8682819/stripe-cli-1.8.11.zip)

**Comment by cjavilla-stripe** [comment]
@vecsdom can you elaborate?

**Comment by vecsdom** [comment]
> {
> 
>   "name": "accept-a-payment",
> 
>   "configureDotEnv": true,
> 
>   "integrations": [
> 
>     {
> 
>       "name": "payment-element",
> 
>       "clients": ["html", "react-cra"],
> 
>       "servers": [
> 
>         "ruby",
> 
>         "node",
> 
>         "python",
> 
>         "php",
> 
>         "java",
> 
>         "go",
> 
>         "dotnet",
> 
>         "node-typescript"
> 
>       ]
> 
>     },
> 
>     {
> 
>       "name": "prebuilt-checkout-page",
> 
>       "clients": ["html", "react-cra", "vue-cva"],
> 
>       "servers": [
> 
>         "ruby",
> 
>         "node",
> 
>         "python",
> 
>         "php",
> 
>         "java",
> 
>         "go",
> 
>         "dotnet"
> 
>       ]
> 
>     },
> 
>     {
> 
>       "name": "custom-payment-flow",
> 
>       "clients": ["html", "react-cra", "ios", "android-kotlin", "ios-swiftui"],
> 
>       "servers": [
> 
>         "ruby",
> 
>         "node",
> 
>         "python",
> 
>         "php",
> 
>         "java",
> 
>         "go",
> 
>         "dotnet",
> 
>         "node-typescript"
> 
>       ]
> 
>     }
> 
>   ]
> 
> }
> 
> [stripe-cli-1.8.11.zip](https://github.com/stripe-samples/accept-a-payment/files/8682819/stripe-cli-1.8.11.zip)
> 
> 
> 
>

**Comment by vecsdom** [comment]
> {
> 
>   "name": "accept-a-payment",
> 
>   "configureDotEnv": true,
> 
>   "integrations": [
> 
>     {
> 
>       "name": "payment-element",
> 
>       "clients": ["html", "react-cra"],
> 
>       "servers": [
> 
>         "ruby",
> 
>         "node",
> 
>         "python",
> 
>         "php",
> 
>         "java",
> 
>         "go",
> 
>         "dotnet",
> 
>         "node-typescript"
> 
>       ]
> 
>     },
> 
>     {
> 
>       "name": "prebuilt-checkout-page",
> 
>       "clients": ["html", "react-cra", "vue-cva"],
> 
>       "servers": [
> 
>         "ruby",
> 
>         "node",
> 
>         "python",
> 
>         "php",
> 
>         "java",
> 
>         "go",
> 
>         "dotnet"
> 
>       ]
> 
>     },
> 
>     {
> 
>       "name": "custom-payment-flow",
> 
>       "clients": ["html", "react-cra", "ios", "android-kotlin", "ios-swiftui"],
> 
>       "servers": [
> 
>         "ruby",
> 
>         "node",
> 
>         "python",
> 
>         "php",
> 
>         "java",
> 
>         "go",
> 
>         "dotnet",
> 
>         "node-typescript"
> 
>       ]
> 
>     }
> 
>   ]
> 
> }
> 
> [stripe-cli-1.8.11.zip](https://github.com/stripe-samples/accept-a-payment/files/8682819/stripe-cli-1.8.11.zip)
> 
> 
> 
>
